### ISSUE TITLE
Graduation Rate Exhibit has 2 Values for 2014

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#82]
Looking into this...

![capture](https://cloud.githubusercontent.com/assets/7928978/5745343/07715942-9bf6-11e4-9c73-635566b2591c.PNG)

**Comment by benjaminrobinson** [comment]
Is this a 4 year and 5 year rate distinction?

**Comment by cmgiven** [comment]
I don't believe so, as other years would have both rates as well. Do you have a school code?

**Comment by benjaminrobinson** [comment]
This is DCPS's LEA numbers...

**Comment by benjaminrobinson** [comment]
LEA code 0001.

**Comment by cmgiven** [comment]
But you're right. The values being shown are both the four year and five year rates from that data file. Have the options for type always been "Four Year ACGR" and "Five Year ACGR"?

@mepps, if you're around, it would be helpful to get your perspective here.

**Comment by benjaminrobinson** [comment]
I'm not sure...this was done by Alex in the new Graduation Aggregators he created.  I know very little about this exhibit overall but the data that feeds it has a "Type" for the types you've mentioned.

**Comment by mepps** [comment]
Hey everyone, looking into this now.

**Comment by mepps** [comment]
To clarify, this is on the dc report card?

**Comment by mepps** [comment]
Found it.

**Comment by benjaminrobinson** [comment]
We were ever going to report 4 and 5 year ACGR on the school report card?  We probably want to suppress the 5 year on the report card but keep it around for the equity report.

**Comment by cmgiven** [comment]
No, we do use both. Equity Report has a toggle between the two. LearnDC proper let's you flip between in the Detail view.

**Comment by mepps** [comment]
I have a front end fix for this.

**Comment by cmgiven** [comment]
Great, thanks Maggie. Good to know.

Note that this is separate from the ACGR discussions that OSSE is having right now.

**Comment by benjaminrobinson** [comment]
Where can you do that in the detail view, Chris?  I don't see it.

**Comment by gwenrr** [comment]
The other issue is two 2014s

**Comment by mepps** [comment]
![screen shot 2015-01-14 at 2 59 32 pm](https://cloud.githubusercontent.com/assets/4406809/5746485/fa491e96-9bfd-11e4-83f3-17fe34626171.png)

Fixed on staging.

**Comment by cmgiven** [comment]
Hmm, you're right, Ben. It's no longer there. I can't remember when that happened.

**Comment by cmgiven** [comment]
Looks good, thanks Maggie.

Ben, I'm closing this issue as the front-end bug has been resolved. Let's open another one to track the data issue you're looking into now.

**Comment by benjaminrobinson** [comment]
Still showing in the detail view...but hidden in the summary view.

**Comment by mepps** [comment]
![screen shot 2015-01-20 at 9 08 24 am](https://cloud.githubusercontent.com/assets/4406809/5818473/e9ce764e-a083-11e4-918c-b40b010230fa.png)

Fixed on staging.

**Comment by cmgiven** [comment]
I'm now seeing a weird bug where the years are out of order. Only on the Detail tab. Should I open a new issue?

http://www.stage.learndc.org/schoolprofiles/view?s=lea-0001#reportcard

**Comment by mepps** [comment]
![screen shot 2015-01-20 at 9 23 34 am](https://cloud.githubusercontent.com/assets/4406809/5818759/0ef3f8f2-a086-11e4-9033-862e4e958d35.png)
Fixed on staging.

**Comment by cmgiven** [comment]
Confirmed and closed.
